name: Make

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: build
        run: |
          sudo apt install libxrandr-dev
          make
